---
title: "Contact"
---

We play in the Sports hall of St Cyres School in Penarth: Sully Rd, Penarth CF64 2XP. There is free onsite parking at the school.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2487.117297134816!2d-3.196627200000001!3d51.437639700000005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x486e048365261c59%3A0xf65ac689c5b09862!2sSt%20Cyres%20School!5e0!3m2!1sen!2suk!4v1736091382705!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

To receive regular updates about the club, join our official WhatsApp group. Only admins can post on this group, so this is the best option if you want to stay up to date with club news without receiving too many messages. It is open to all members and non-members. Join by contacting us at [penarthttc@gmail.com](mailto:penarthttc@gmail.com).

To be part of the community, join our informal WhatsApp group. It is open to all club members and allies, who are welcome to post at any time between 8am and 9.30pm. Join by contacting us at [penarthttc@gmail.com](mailto:penarthttc@gmail.com).


For all other inquiries, please email us at [penarthttc@gmail.com](mailto:penarthttc@gmail.com).


