---
title: "Safeguarding"
---

The Penarth Table Tennis Club is committed to being a safe place. Our safeguarding policy can be found [here](Link to be added once a launch date is known). It notably includes information about the responsibilities of club officials, how to raise a concern, and how it will be dealt with.

Safeguarding is everyone’s responsibility. Everyone is encouraged to remain vigilant at all times and to report concerns to the club’s Safeguarding Officer. Committee members, volunteers, and parents are encouraged to learn more about safeguarding, for instance by consulting the resources provided by Table Tennis Wales or by taking [this free online course](Link to be added).

The club’s Safeguarding Officer is Achille. He attends most sessions run by the club and can be contacted at [penarthttc@gmail.com](mailto:penarthttc@gmail.com).

St Cyres School Centre has its own safeguarding policy, which can be found [here](https://www.stcyres.org/page/?title=safeguarding&pid=87). Table Tennis Wales also has a safeguarding policy, [here](https://tabletennis.wales/safeguarding/), as well as a range of safeguarding documents. Its Safeguarding Officer is Martyn, who can be contacted on [safeguarding@tabletennis.wales](mailto:safeguarding@tabletennis.wales) or on 07500046861.
