---
title: "Support"
---

The Penarth Table Tennis Club is a non-profit, unincorporated association. The income we generate through our table tennis activities is entirely used to cover our running costs. Our main expenses include:

-	Renting the sports hall at St Cyres School. We are charged just under £40 per hour, i.e. £60 per session.
-	Renewing our equipment, such as tables, nets, balls, and barriers.
-	Renewing our membership affiliation with Table Tennis Wales.

We benefitted from the generous support of the Be Active Wales Fund, funded by the National Lottery, who awarded us nearly £3,000 to setup of the club. The grant was primarily used to train volunteers and purchase equipment.

We set our membership fee at the minimum price to break even. For the club to grow, we rely on the gracious support of our supporters. With sufficient support, we may be able to organise community events and activities for children.

If you would like to make a donation, get in touch to ask for our bank details. You can also find us here [XXX] on PayPal Giving. Don’t forget to let us know you have made a donation so we can say thank you!

We are also open to partnership opportunities. If you would like to contact us about a proposal, see our contact page.

